language: python
env: PYTHON=python3

matrix:
  include:
    - dist: bionic
      python: 3.6
    - dist: bionic
      python: 3.7
    - dist: focal
      python: 3.8
    - dist: focal
      python: pypy3
    - os: osx
      language: generic
    - os: windows
      # Windows doesn't support python or even generic language
      language: cpp
      env: PYTHON=/c/Python38/python

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export "PATH=$PATH;C:\msys64\mingw64\bin"; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y python; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then wget "http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20180531.tar.xz"; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then 7z e msys2-base-x86_64-20180531.tar.xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then 7z x -y msys2-base-x86_64-20180531.tar -oc:\\; fi
  # We need powershell because Travis' bash and MSYS2's bash rely on conflicting libraries
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell "C:\msys64\usr\bin\bash -lc 'pacman -S mingw-w64-x86_64-gtk3 --noconfirm'"; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew pin numpy gdal postgis; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cairo gdk-pixbuf; fi

  - $PYTHON -m pip install --upgrade setuptools
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then $PYTHON -m pip install -e .[test,xcb]; fi
  - if [[ "$TRAVIS_OS_NAME" != "linux" ]]; then $PYTHON -m pip install -e .[test]; fi

script:
  - $PYTHON setup.py test
